micronaut:
  application:
    name: microapp
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: tian1990
    schema-generate: CREATE_DROP
    dialect: POSTGRES
rabbitmq.uri: amqp://localhost:5672

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
    packages-to-scan:
      - microapp.entity
